### ISSUE TITLE
System.IO.FileNotFoundException: Could not load file or assembly 'Mono.Cecil, Version=0.11.1.0, Culture=neutral, PublicKeyToken=50cebf1cceb9d05e'.

### ISSUE THREAD

**Issue by pengweiqhca** [pardeike/Harmony#255]
**Describe the bug**
ILPack not executing on netcoreapp3.x, or package files should comtains Mono.Cecil and MonoMode.Common on netcoreapp3.x

**Expected behavior**
No exception

**Screenshots / Code**
System.IO.FileNotFoundException: Could not load file or assembly 'Mono.Cecil, Version=0.11.1.0, Culture=neutral, PublicKeyToken=50cebf1cceb9d05e'. 系统找不到指定的文件。
File name: 'Mono.Cecil, Version=0.11.1.0, Culture=neutral, PublicKeyToken=50cebf1cceb9d05e'
   at HarmonyLib.HarmonySharedState.CreateModule()
   at HarmonyLib.HarmonySharedState.GetState()
   at HarmonyLib.HarmonySharedState.GetPatchInfo(MethodBase method)
   at HarmonyLib.PatchProcessor.Patch()
   at HarmonyLib.Harmony.Patch(MethodBase original, HarmonyMethod prefix, HarmonyMethod postfix, HarmonyMethod transpiler, HarmonyMethod finalizer)

**Runtime environment (please complete the following information):**
 - OS: Windows 10, 64bit
 - .NET Core 3.1
 - Harmony version 2.0.0.5
 - Console 

**Additional context**
![image](https://user-images.githubusercontent.com/3982826/74995086-c83ecb80-548a-11ea-8521-9cca5ce1eec5.png)

**Comment by pengweiqhca** [comment]
Package files not comtains `Mono.Cecil` and `MonoMode.Common`

**Comment by pengweiqhca** [comment]
``` bash
git clone https://github.com/pengweiqhca/HarmonyDemo.git
cd HarmonyDemo/HarmonyDemo
```
``` bash
dotnet run -f netcoreapp3.1
```
You will get a exception.
``` bash
dotnet run -f net471
```
You will not get a exception
