### ISSUE TITLE
Failed to work for Net45 on VS2017 + Win10

### ISSUE THREAD

**Issue by hcoona** [pardeike/Harmony#27]
I'm following the Wiki to get start Harmony but failed with following exception (full log at end):

> Unhandled Exception: System.NotSupportedException: Wrong MethodAttributes or CallingConventions for DynamicMethod. Only public, static, standard supported

Environment:
- Harmony 1.0.9.1 
- Windows 10
- VS 2017
- .NET Framework 4.5

Code:

```csharp
using System;
using System.Globalization;
using System.Reflection;
using System.Threading;
using Harmony;

namespace TestHarmony
{
    class Program
    {
        static void Main(string[] args)
        {
            Thread.CurrentThread.CurrentCulture = CultureInfo.InvariantCulture;
            Thread.CurrentThread.CurrentUICulture = CultureInfo.InvariantCulture;
            var harmony = HarmonyInstance.Create("test");
            harmony.PatchAll(Assembly.GetExecutingAssembly());
        }

        [HarmonyPatch(typeof(String))]
        [HarmonyPatch("IndexOf")]
        [HarmonyPatch(new Type[] { typeof(char), typeof(int) })]
        class Patch
        {
            static void Prefix()
            {
            }
        }
    }
}
```

Full console error message:
```
Unhandled Exception: System.NotSupportedException: Wrong MethodAttributes or CallingConventions for DynamicMethod. Only public, static, standard supported
   at System.Reflection.Emit.DynamicMethod.CheckConsistency(MethodAttributes attributes, CallingConventions callingConvention)
   at System.Reflection.Emit.DynamicMethod.Init(String name, MethodAttributes attributes, CallingConventions callingConvention, Type returnType, Type[] signature, Type owner, Module m, Boolean skipVisibility, Boolean transparentMethod, StackCrawlMark& stackMark)
   at System.Reflection.Emit.DynamicMethod..ctor(String name, MethodAttributes attributes, CallingConventions callingConvention, Type returnType, Type[] parameterTypes, Type owner, Boolean skipVisibility)
   at Harmony.DynamicTools.CreateDynamicMethod(MethodBase original, String suffix) in C:\Users\Admin\Source\Repos\Harmony\Harmony\Tools\DynamicTools.cs:line 23
   at Harmony.MethodPatcher.CreatePatchedMethod(MethodBase original, List`1 prefixes, List`1 postfixes, List`1 transpilers) in C:\Users\Admin\Source\Repos\Harmony\Harmony\MethodPatcher.cs:line 23
   at Harmony.PatchFunctions.UpdateWrapper(MethodBase original, PatchInfo patchInfo) in C:\Users\Admin\Source\Repos\Harmony\Harmony\PatchFunctions.cs:line 59
   at Harmony.PatchProcessor.Patch() in C:\Users\Admin\Source\Repos\Harmony\Harmony\PatchProcessor.cs:line 63
   at Harmony.HarmonyInstance.<PatchAll>b__6_0(Type type) in C:\Users\Admin\Source\Repos\Harmony\Harmony\HarmonyInstance.cs:line 68
   at Harmony.CollectionExtensions.Do[T](IEnumerable`1 sequence, Action`1 action) in C:\Users\Admin\Source\Repos\Harmony\Harmony\Tools\Extensions.cs:line 45
   at Harmony.HarmonyInstance.PatchAll(Assembly assembly) in C:\Users\Admin\Source\Repos\Harmony\Harmony\HarmonyInstance.cs:line 61
   at TestHarmony.Program.Main(String[] args) in D:\VsProjects\TestHarmony\TestHarmony\Program.cs:line 20
```

**Comment by pardeike** [comment]
You are not using the master branch that contains the fixes for non-mono versions of Harmony. See corresponding Issues.

**Comment by pardeike** [comment]
I’ll close this as a duplicate.
