### ISSUE TITLE
return transpiler IEnumerable<CodeInstruction> from MethodBase.GetILAsByteArray()

### ISSUE THREAD

**Issue by sake402** [pardeike/Harmony#305]
Say I have a MethodInfo of another type inside a transpiler function for a particular type, how do I get IEnumerable&lt;CodeInstruction&gt; from the MethodBase.GetILAsByteArray().

**Comment by pardeike** [comment]
Use one of these methods but beware that opcodes are relative to their current method and when they refer to, for example, method arguments or return a value it will only be valid inside the original method. Don’t expect it to work “out of the box” - you can modify the instructions of course:
- https://harmony.pardeike.net/api/HarmonyLib.PatchProcessor.html#HarmonyLib_PatchProcessor_GetCurrentInstructions_System_Reflection_MethodBase_System_Int32_System_Reflection_Emit_ILGenerator_
- https://harmony.pardeike.net/api/HarmonyLib.PatchProcessor.html#HarmonyLib_PatchProcessor_GetOriginalInstructions_System_Reflection_MethodBase_System_Reflection_Emit_ILGenerator_
- https://harmony.pardeike.net/api/HarmonyLib.PatchProcessor.html#HarmonyLib_PatchProcessor_ReadMethodBody_System_Reflection_MethodBase_

**Comment by sake402** [comment]
Yes. I understand, thank you.
The method I am patching is exactly the same old method, so they have exactly the same signature(arguments and return)

**Comment by sake402** [comment]
I just tested with this code
```
Type newCompiledType = context.NewType;
            var newRenderTree = newCompiledType.GetMethod("BuildRenderTree", BindingFlags.NonPublic | BindingFlags.Instance);
            var newCodes = PatchProcessor.ReadMethodBody(newRenderTree);
            return newCodes.Select(c => new CodeInstruction(c.Key, c.Value)).ToArray();
```
It works.

But as soon as I have an If statement in the newly compiled code, I got this exception

```
Unexpected unemittable operand type HarmonyLib.ILInstruction
   at MonoMod.Utils.Cil.ILGeneratorShimExt.DynEmit(ILGenerator il, Object[] emitArgs)
   at MonoMod.Utils.Cil.ILGeneratorShimExt.DynEmit(ILGenerator il, OpCode opcode, Object operand)
   at HarmonyLib.MethodBodyReader.<>c__DisplayClass21_0.<FinalizeILCodes>b__2(CodeInstruction codeInstruction)
   at HarmonyLib.CollectionExtensions.Do[T](IEnumerable`1 sequence, Action`1 action)
   at HarmonyLib.MethodBodyReader.FinalizeILCodes(Emitter emitter, List`1 transpilers, List`1 endLabels, Boolean& hasReturnCode)
   at HarmonyLib.MethodPatcher.CreateReplacement(Dictionary`2& finalInstructions)
   at HarmonyLib.PatchFunctions.UpdateWrapper(MethodBase original, PatchInfo patchInfo)
   at HarmonyLib.PatchProcessor.Patch()
   at HarmonyLib.Harmony.Patch(MethodBase original, HarmonyMethod prefix, HarmonyMethod postfix, HarmonyMethod transpiler, HarmonyMethod finalizer)
   at LivingThing.LiveBlazor.Blazor.<>c__DisplayClass7_0.<<Live>b__3>d.MoveNext() in E:\Apps\LivingThing\Tools\LivingThing.LiveBlazor\Blazor.cs:line 245
```

**Comment by pardeike** [comment]
Obviously the code instructions you copied refer to local variables and jump labels that are created for the other method. A method does not only consist of instructions therefore I don’t recommend copying instructions like that over unless you know exactly what you do. 

That’s the reason you can inject the ILGenerator that Harmony uses and will use to create the final replacement method and use it to define labels and local variables. This makes even more sense if you consider that transpilers need to work chained in case multiple mod patch the same method.

**Comment by sake402** [comment]
Thank you. I took you advice and did this with the hope creating the label myself but I have exception on 
```
case sbyte i:
      generator.Emit(code.Key, i);
```
code.Key is OpCodes.Ldc_I4_S
and code.Value is 9
```
        public static IEnumerable<CodeInstruction> ReplaceBuildRenderTree(IEnumerable<CodeInstruction> instructions, ILGenerator generator)
        {
            var context = liveContexts[currentType];//[typeof(TComponent)];
            Type newCompiledType = context.NewType;
            var newRenderTree = newCompiledType.GetMethod("BuildRenderTree", BindingFlags.NonPublic | BindingFlags.Instance);
            var newCodes = PatchProcessor.ReadMethodBody(newRenderTree);
            foreach(var code in newCodes)
            {
                switch (code.Key.OperandType)
                {
                    default:
                        switch (code.Value)
                        {
                            case bool i:
                                generator.Emit(code.Key, i == false ? 0 : 1);
                                break;
                            case byte i:
                                generator.Emit(code.Key, i);
                                break;
                            case sbyte i:
                                generator.Emit(code.Key, i);
                                break;
                            case int i:
                                generator.Emit(code.Key, i);
                                break;
                            case uint i:
                                generator.Emit(code.Key, i);
                                break;
                            case long i:
                                generator.Emit(code.Key, i);
                                break;
                            case float i:
                                generator.Emit(code.Key, i);
                                break;
                            case double i:
                                generator.Emit(code.Key, i);
                                break;
                            case string i:
                                generator.Emit(code.Key, i);
                                break;
                            case Type i:
                                generator.Emit(code.Key, i);
                                break;
                            case MethodInfo i:
                                generator.Emit(code.Key, i);
                                break;
                            default:
                                if (code.Value != null)
                                {

                                }
                                generator.Emit(code.Key);
                                break;
                        }
                        break;
                    case OperandType.ShortInlineBrTarget:
                    case OperandType.InlineBrTarget:
                        break;
                }
            }
            //return newCodes.Select(c => new CodeInstruction(c.Key, c.Value)).ToArray();
            //var newInstructions = newRenderTree.GetInstructions();
            //var newCodeInstructions = newInstructions.Select(i =>
            //{
            //    //var operand = i.Operand;
            //    //if (operand is Instruction ins)
            //    //{
            //    //    operand = new CodeInstruction(ins.OpCode, ins.Operand);
            //    //}
            //    return new CodeInstruction(i.OpCode, operand);
            //}).ToArray();
            //return newCodeInstructions;
            return new CodeInstruction[] { };
        }

```

**Comment by sake402** [comment]
Hi pardeike.
Finally got it working with this.

```
            var newInstructions = newRenderTree.GetInstructions();
            var labelledInstructions = newInstructions.Where(l => l.Operand is Instruction);
            Dictionary<Instruction, Label> instructionLabels = new Dictionary<Instruction, Label>();
            foreach(var instruction in labelledInstructions)
            {
                instructionLabels[instruction.Operand as Instruction] = generator.DefineLabel();
            }
            foreach(var instruction in newInstructions)
            {
                Label label;
                if (instructionLabels.TryGetValue(instruction, out label))
                {
                    generator.MarkLabel(label);
                }
                switch (instruction.OpCode.OperandType)
                {
                    default:
                        switch (instruction.Operand)
                        {
                            case bool i:
                                generator.Emit(instruction.OpCode, i == false ? 0 : 1);
                                break;
                            case byte i:
                                generator.Emit(instruction.OpCode, i);
                                break;
                            case sbyte i:
                                //STRANGE: pushing an int8 onto stack throws object reference exception
                                //so we change the instruction to push int32
                                if (instruction.OpCode == OpCodes.Ldc_I4_S) 
                                {
                                    generator.Emit(OpCodes.Ldc_I4, (int)i);
                                }
                                else
                                {
                                    generator.Emit(instruction.OpCode, i);
                                }
                                break;
                            case int i:
                                generator.Emit(instruction.OpCode, i);
                                break;
                            case uint i:
                                generator.Emit(instruction.OpCode, i);
                                break;
                            case long i:
                                generator.Emit(instruction.OpCode, i);
                                break;
                            case float i:
                                generator.Emit(instruction.OpCode, i);
                                break;
                            case double i:
                                generator.Emit(instruction.OpCode, i);
                                break;
                            case string i:
                                generator.Emit(instruction.OpCode, i);
                                break;
                            case Type i:
                                generator.Emit(instruction.OpCode, i);
                                break;
                            case MethodInfo i:
                                generator.Emit(instruction.OpCode, i);
                                break;
                            default:
                                if (instruction.Operand  != null)
                                {

                                }
                                generator.Emit(instruction.OpCode);
                                break;
                        }
                        break;
                    case OperandType.ShortInlineBrTarget:
                    case OperandType.InlineBrTarget:
                        Label branchLabel = instructionLabels[instruction.Operand as Instruction];
                        generator.Emit(instruction.OpCode, branchLabel);
                        break;
                }
            }

```

Note the comment in ``case sbyte i``. 
I think its strange that emitting opcode OpCodes.Ldc_I4_S with sbyte operand throws a null reference exception. I had to change the code to emit OpCodes.Ldc_I4 with int parameter instead

What do you think?

**Comment by pardeike** [comment]
You should never use the generator to emit codes. The whole idea with the abstraction of CodeInstruction is to give Hamony the ability to emit it itself. When multiple patches patch the same method, there can be calls to prefixes or other transpilers that would not work if you emit the moment your transpiler is called. 

Only use it to create new labels and new local variables.
