### ISSUE TITLE
Harmony can throw InvalidOperationException when the patch is inside a generic class

### ISSUE THREAD

**Issue by bcmpinc** [pardeike/Harmony#418]
**Describe the bug**
Calling Harmony.Patch with a method in a generic class works as long as no other mods are patching the same function. However when other mods do patch it and thus the method is called again, it fails with an InvalidOperationException: Late bound operations cannot be performed on types or methods for which ContainsGenericParameters is true. 

It seems that some type information is lost while copying around the MethodInfo.

**To Reproduce**
1. The original method and its signature and class
This fails on any method.
2. The patch code (This is the entire mod)
Class1.cs
```
using HarmonyLib;
using StardewModdingAPI;
using StardewValley;
using System.Collections.Generic;
using System.Reflection;
using System.Reflection.Emit;

namespace GenericBug {
    public class GenericClass<T> {
        public static IEnumerable<CodeInstruction> ApplyPatch(MethodBase original, ILGenerator generator, IEnumerable<CodeInstruction> instructions) {
            return instructions;
        }
    }

    public class ModEntry : Mod {
        public override void Entry(IModHelper helper) {
            var harmony = new Harmony("GenericBug");
            var apply  = AccessTools.Method(typeof(GenericClass<ModEntry>), nameof(GenericClass<ModEntry>.ApplyPatch));
            var method = AccessTools.Method(typeof(Game1), nameof(Game1.IsSnowingHere));
            harmony.Patch(method, null, null, new HarmonyMethod(apply)); // A
            harmony.Patch(method, null, null, new HarmonyMethod(apply)); // B
        }
    }
}
```

manifest.json
```
{
  "Name": "GenericBug",
  "Author": "bcmpinc",
  "Version": "100.0",
  "Description": "Breaks SDV.",
  "UniqueID": "bcmpinc.GenericBug",
  "EntryDll": "GenericBug.dll",
  "MinimumApiVersion": "3.12.0"
}
```

GenericBug.csproj
```
<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<AssemblyName>GenericBug</AssemblyName>
		<RootNamespace>GenericBug</RootNamespace>
		<Version>100.0</Version>
		<TargetFramework>net452</TargetFramework>
		<ResolveAssemblyWarnOrErrorOnTargetArchitectureMismatch>None</ResolveAssemblyWarnOrErrorOnTargetArchitectureMismatch>

		<EnableHarmony>true</EnableHarmony>
	</PropertyGroup>

	<!-- required for MonoDevelop compatibility -->
	<PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Release|Any CPU' " />

	<ItemGroup>
		<PackageReference Include="Pathoschild.Stardew.ModBuildConfig" Version="3.3.0" />
	</ItemGroup>
</Project>
```

3. The output of the Harmony debug log
How do I make one?

4. The stacktrace or other errors
[14:03:23 ERROR GenericBug] Mod crashed on entry and might not work correctly. Technical details:
System.InvalidOperationException: Late bound operations cannot be performed on types or methods for which ContainsGenericParameters is true.
   at System.Reflection.RuntimeMethodInfo.ThrowNoInvokeException()
   at System.Reflection.RuntimeMethodInfo.InvokeArgumentsCheck(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at HarmonyLib.CodeTranspiler.<>c__DisplayClass12_0.<GetResult>b__0(MethodInfo transpiler)
   at System.Collections.Generic.List`1.ForEach(Action`1 action)
   at HarmonyLib.CodeTranspiler.GetResult(ILGenerator generator, MethodBase method)
   at HarmonyLib.MethodBodyReader.FinalizeILCodes(Emitter emitter, List`1 transpilers, List`1 endLabels, Boolean& hasReturnCode)
   at HarmonyLib.MethodCopier.Finalize(Emitter emitter, List`1 endLabels, Boolean& hasReturnCode)
   at HarmonyLib.MethodPatcher.CreateReplacement(Dictionary`2& finalInstructions)
   at HarmonyLib.PatchFunctions.UpdateWrapper(MethodBase original, PatchInfo patchInfo)
   at HarmonyLib.PatchProcessor.Patch()
   at HarmonyLib.Harmony.Patch(MethodBase original, HarmonyMethod prefix, HarmonyMethod postfix, HarmonyMethod transpiler, HarmonyMethod finalizer)
   at GenericBug.ModEntry.Entry(IModHelper helper) in C:\Users\bauke\source\repos\GenericBug\GenericBug\Class1.cs:line 22
   at StardewModdingAPI.Framework.SCore.LoadMods(IModMetadata[] mods, JsonHelper jsonHelper, ContentCoordinator contentCore, ModDatabase modDatabase) in C:\source\_Stardew\SMAPI\src\SMAPI\Framework\SCore.cs:line 1579

**Expected behavior**
ApplyPatch should be executed twice, without it throwing an exception

**Runtime environment (please complete the following information):**
- OS: Windows 10 home 20H2, 64-bit
- .NET version 4.5.2
- Harmony version 2.1.0
- Stardew Valley 1.5.4
- SMAPI 3.12.0

**Additional context**
When the line tagged with B is removed, no exception is thrown.
For this example, I picked an arbitrary method to be patched (Game1.IsSnowingHere).

There's no easy way for me to eliminate the type parameter as I'm using ApplyPatch as a wrapper/proxy. One option I tried is using a Lambda (see below), but this requires an instance parameter to be passed (even when the 'static' keyword is added to the lambda function).
`var apply = new Func<MethodBase, ILGenerator, IEnumerable<CodeInstruction>, IEnumerable<CodeInstruction>>((original, generator, instructions) => ApplyPatch(original, generator, instructions)).Method;`

**Comment by pardeike** [comment]
Harmony does not support generic patch classes. There are currently no plans to support them because of the general implications and undocumented nature of generics as well as a complete break with backwards compatibility.

**Comment by bcmpinc** [comment]
This used to work fine in 1.2.0.1.

**Comment by pardeike** [comment]
That might be. But 1.2 did not support all the common .NET versions and platforms. Some .NET versions can’t even serialize MethodBase and I have to work around that. I have no idea how I would do that with the complexity of generics and keep it backwards compatible is another problem.
