### ISSUE TITLE
Unable to Get Data of Internal field in Public Class

### ISSUE THREAD

**Issue by WesternGamer** [pardeike/Harmony#438]
**Describe the bug**
I was patching a method in a game game called Space Engineers and I came upon a field that was marked as Internal in a public class. I attempted to use the field in the patched method but It caused an exception:
```
HarmonyLib.HarmonyException: Patching exception in method System.Void Sandbox.Game.Entities.Character.MyCharacter::DieInternal() ---> System.ArgumentException: No such field defined in class Sandbox.Game.Entities.Character.MyCharacter, Sandbox.Game, Version=0.1.1.0, Culture=neutral, PublicKeyToken=null
Parameter name: CurrentRemoteControl
   at HarmonyLib.MethodPatcher.EmitCallParameter(MethodInfo patch, Dictionary`2 variables, LocalBuilder runOriginalVariable, Boolean allowFirsParamPassthrough, LocalBuilder& tmpObjectVar, List`1 tmpBoxVars)
   at HarmonyLib.MethodPatcher.<>c__DisplayClass32_0.<AddPrefixes>b__0(MethodInfo fix)
   at HarmonyLib.CollectionExtensions.Do[T](IEnumerable`1 sequence, Action`1 action)
   at HarmonyLib.MethodPatcher.CreateReplacement(Dictionary`2& finalInstructions)
   at HarmonyLib.PatchFunctions.UpdateWrapper(MethodBase original, PatchInfo patchInfo)
   at HarmonyLib.PatchClassProcessor.ProcessPatchJob(Job job)
   --- End of inner exception stack trace ---
   at HarmonyLib.PatchClassProcessor.ReportException(Exception exception, MethodBase original)
   at HarmonyLib.PatchClassProcessor.Patch()
   at HarmonyLib.CollectionExtensions.Do[T](IEnumerable`1 sequence, Action`1 action)
   at RDR2DeathScreen.Main.Init(Object gameInstance)
   at avaness.PluginLoader.PluginInstance.Init(Object gameInstance)
```

**To Reproduce**
1. The original method and its signature and class:
```
// Token: 0x17000F47 RID: 3911
	// (get) Token: 0x06007DA0 RID: 32160 RVA: 0x002D32CB File Offset: 0x002D14CB
	// (set) Token: 0x06007DA1 RID: 32161 RVA: 0x002D32D3 File Offset: 0x002D14D3
	internal IMyControllableEntity CurrentRemoteControl { get; set; }
```
```
// Token: 0x02001033 RID: 4147
	[MyEntityType(typeof(MyObjectBuilder_Character), true)]
	[StaticEventOwner]
	public class MyCharacter : MySkinnedEntity, IMyCameraController, IMyControllableEntity, IMyControllableEntity, IMyInventoryOwner, IMyUseObject, IMyDestroyableObject, IMyDecalProxy, IMyCharacter, VRage.ModAPI.IMyEntity, VRage.Game.ModAPI.Ingame.IMyEntity, IMyEventProxy, IMyEventOwner, IMyComponentOwner<MyIDModule>, IMySyncedEntity, IMyTrackTrails, IMyParallelUpdateable
```
2. The patch code
```
[HarmonyPatch(typeof(MyCharacter), "DieInternal")]
    internal class ExamplePatch
    {
        private static bool Prefix(MyCharacter __instance, ref MyGuiScreenBase ___m_InventoryScreen, ref MyCharacterBreath ___m_breath, 
			ref IMyControllableEntity ___CurrentRemoteControl, ref MyCharacterMovementEnum ___m_currentMovementState, 
			ref MyEntityCameraSettings ___m_cameraSettingsWhenAlive, ref long ___m_deadPlayerIdentityId, ref bool ___m_isFalling, 
			ref bool ___m_animationCommandsEnabled, ref bool ___m_isInFirstPerson, ref float ___m_currentLootingCounter, 
			ref MyCharacterDefinition ___m_characterDefinition, ref Action<MyCharacter> ___CharacterDied, ref Action<MyCharacter> ___OnCharacterDied,
			ref MyPhysicsBody ___m_aimAssistPhysics)
        { 
               //Code 
        }
```
3. The output of the Harmony debug log: Covered in description of issue.
4. The stacktrace or other errors: Covered in description of issue.

**Expected behavior**
I am expecting Harmony to get the data from the field to be used in the patched method. 

**Screenshots / Code**
None

**Runtime environment (please complete the following information):**
 - OS: Windows 11 x64
 - .NET version: .NET Framework 4.8
 - Harmony version: 2.1.1.0
- Name of game or host application: Space Engineers

**Additional context**
None

**Comment by pardeike** [comment]
That’s not a field. It’s a property and as such cannot be injected. You need to use the instance with it to get/set values in it yourself inside the patch.

**Comment by WesternGamer** [comment]
> That’s not a field. It’s a property and as such cannot be injected. You need to use the instance with it to get/set values in it yourself inside the patch.

Ah that's why, thanks for the explanation.
