### ISSUE TITLE
HarmonyPatchAll doesn't seem to work?

### ISSUE THREAD

**Issue by dazoe** [pardeike/Harmony#439]
**Describe the bug**
When trying to use HarmonyPatchAll it throws exception:
```
HarmonyLib.HarmonyException: 'Patching exception in method System.Void HarmonyTest.SomeClass::.ctor()'
Inner Exception
ArgumentException: You cannot combine TargetMethod, TargetMethods or PatchAll with individual annotations [HarmonyTest.SomeClass]
```

**To Reproduce**
```C#
	class SomeClass {
		public string SomeMethod() {
			return "World!";
		}
	}

	[HarmonyPatch(typeof(SomeClass))]
	[HarmonyPatchAll]
	class SomeClassPatch {
		static void Prefix(SomeClass __instance, MethodBase __originalMethod) {
			Console.WriteLine("SomeClass:{0}(...)", __originalMethod.Name);
		}
	}
	
	class Program {
		static void Main(string[] args) {
			Harmony.DEBUG = true;
			var harmony = new Harmony("HarmonyTest");
			harmony.PatchAll();
			Console.WriteLine("Hello, {0}!", new SomeClass().SomeMethod());
			Console.ReadLine();
		}
	}
```

The output of the Harmony debug log:
```
### Harmony id=HarmonyTest, version=2.1.1.0, location=C:\Users\Dave\source\repos\HarmonyTest\bin\Debug\0Harmony.dll, env/clr=4.0.30319.42000, platform=Win32NT, ptrsize:runtime/env=4/Bits64, Windows
### Started from static System.Void HarmonyTest.Program::Main(System.String[] args), location C:\Users\Dave\source\repos\HarmonyTest\bin\Debug\HarmonyTest.exe
### At 2021-12-14 05.31.23
### Exception from user "HarmonyTest", Harmony v2.1.1.0
### Original: System.Void HarmonyTest.SomeClass::.ctor()
### Patch class: HarmonyTest.SomeClassPatch
### System.ArgumentException: You cannot combine TargetMethod, TargetMethods or PatchAll with individual annotations [HarmonyTest.SomeClass]
###    at HarmonyLib.PatchClassProcessor.BulkPatch(List`1 originals, MethodBase& lastOriginal)
###    at HarmonyLib.PatchClassProcessor.Patch()
```

Full exception details:
```
HarmonyLib.HarmonyException
  HResult=0x80131500
  Message=Patching exception in method System.Void HarmonyTest.SomeClass::.ctor()
  Source=0Harmony
  StackTrace:
   at HarmonyLib.PatchClassProcessor.ReportException(Exception exception, MethodBase original)
   at HarmonyLib.PatchClassProcessor.Patch()
   at HarmonyLib.Harmony.<PatchAll>b__10_0(Type type)
   at HarmonyLib.CollectionExtensions.Do[T](IEnumerable`1 sequence, Action`1 action)
   at HarmonyLib.Harmony.PatchAll(Assembly assembly)
   at HarmonyLib.Harmony.PatchAll()
   at HarmonyTest.Program.Main(String[] args) in C:\Users\Dave\source\repos\HarmonyTest\Program.cs:line 24

  This exception was originally thrown at this call stack:
    HarmonyLib.PatchClassProcessor.BulkPatch(System.Collections.Generic.List<System.Reflection.MethodBase>, ref System.Reflection.MethodBase)
    HarmonyLib.PatchClassProcessor.Patch()

Inner Exception 1:
ArgumentException: You cannot combine TargetMethod, TargetMethods or PatchAll with individual annotations [HarmonyTest.SomeClass]
```

**Expected behavior**
Use same Prefix patch on all methods of the give class.

**Runtime environment (please complete the following information):**
 - OS: Windows 11 64bit
 - .NET version: 4.7.2
 - Harmony version: 2.1.1.0

**Additional context**
I believe the problem to be in PatchClassProcessor:BulkPatch. There is an if statement checking if (info.declaringType is object). If i remove that check then the PatchAll works as expected, mostly. If I try injecting __result for example it will throw an exception "Cannot get result from void method " but that's to be expected when trying to use the same prefix for multiple methods.

**Comment by pardeike** [comment]
Fixed in https://github.com/pardeike/Harmony/commit/9e03ed3f9c984bd10334f2707a8a53a0a56452af

**Comment by pardeike** [comment]
Note: your conclusion on "Cannot get result from void method" is wrong. It's the constructor that has a void return type and thus it cannot inject __result.
