### ISSUE TITLE
HarmonyLib.FileLog exception for empty string Environment.SpecialFolder.Desktop

### ISSUE THREAD

**Issue by Fasjeit** [pardeike/Harmony#442]
**Description**
When trying to run Harmony in docker container (running by default as root user) I get the following exception:

```
Error Message:
   System.TypeInitializationException : The type initializer for 'HarmonyLib.FileLog' threw an exception.
---- System.ArgumentException : Path cannot be the empty string or all whitespace. (Parameter 'path')
  Stack Trace:
     at HarmonyLib.PatchClassProcessor.ReportException(Exception exception, MethodBase original)
   at HarmonyLib.PatchClassProcessor.Patch()
   at HarmonyLib.Harmony.<PatchAll>b__10_0(Type type)
   at HarmonyLib.CollectionExtensions.Do[T](IEnumerable`1 sequence, Action`1 action)
   at HarmonyLib.Harmony.PatchAll(Assembly assembly)
   at HarmonyLib.Harmony.PatchAll()
   at LibCore.Detours.MasterAlgorithms.Initialize() in /builds/cloud/misc/libcore/src/LibCore.Security.Cryptography.Algorithms/Detours/MasterAlgorithms.cs:line 55
   at System.Security.Cryptography.Encryption.KeyExchange.Tests.DetourFixture..ctor() in /builds/cloud/misc/libcore/tests/LibCore.Security.Cryptography.Csp.Tests/GostSharedSecretTest.cs:line 17
----- Inner Stack Trace -----
   at System.IO.Directory.CreateDirectory(String path)
   at HarmonyLib.FileLog..cctor()
```
`Harmony.DEBUG` was not set in code.

It looks like for root user (at least in docker container) `Environment.SpecialFolder.Desktop` returns empty string, causing the exception.

https://github.com/pardeike/Harmony/blob/5bd23f3fadfd248fdcc589b5564aac4905cba5d7/Harmony/Tools/FileLog.cs#L16-L28

**Current workaround**
Specifying `HARMONY_LOG_FILE` environment variable to some non-empty existing path. 
```bash
export HARMONY_LOG_FILE="/home/la"
```

**Runtime environment:**
 - OS: Ubuntu 20.04.3 LTS
 - .NET version: dotnet 6.0
 - Harmony version: 2.1.1
 - Docker version: 20.10.12

**Comment by pardeike** [comment]
That’s not a “workaround”. That the correct and intended way to solve this.

**Comment by Fasjeit** [comment]
Ok, got it, thank you.

Just looks a little bit weird to me to set Environment variable even with disabled logging.

**Comment by pardeike** [comment]
If you look at https://github.com/pardeike/Harmony/blob/9e03ed3f9c984bd10334f2707a8a53a0a56452af/Harmony/Public/PatchClassProcessor.cs#L242 you see that it only logs when debugging is on which it should not inside a container.

**Comment by Fasjeit** [comment]
It turns out one `HarmonyMethod` in my code had debug which cased the initial problem.... my bad.
Everything seems working properly now.

Thank you again.
