### ISSUE TITLE
Random patching exception

### ISSUE THREAD

**Issue by Guluis** [pardeike/Harmony#444]
Serializer randomly catches an exception during patching.
Stack trace:
System.Text.Json.JsonException: The JSON value could not be converted to HarmonyLib.Patch[]. Path: $.prefixes[0] | LineNumber: 0 | BytePositionInLine: 14.
 ---> System.InvalidOperationException: Cannot get the value of a token type 'StartObject' as a number.
   at System.Text.Json.Utf8JsonReader.TryGetInt32(Int32& value)
   at System.Text.Json.Utf8JsonReader.GetInt32()
   at HarmonyLib.PatchJsonConverter.Read(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options)
   at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.Converters.IEnumerableDefaultConverter`2.OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, TCollection& value)
   at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.JsonPropertyInfo`1.ReadJsonAndSetMember(Object obj, ReadStack& state, Utf8JsonReader& reader)
   at System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1.OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   --- End of inner exception stack trace ---
   at System.Text.Json.ThrowHelper.ReThrowWithPath(ReadStack& state, Utf8JsonReader& reader, Exception ex)
   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   at System.Text.Json.JsonSerializer.ReadCore[TValue](JsonConverter jsonConverter, Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   at System.Text.Json.JsonSerializer.ReadCore[TValue](Utf8JsonReader& reader, Type returnType, JsonSerializerOptions options)
   at System.Text.Json.JsonSerializer.Deserialize[TValue](ReadOnlySpan`1 utf8Json, JsonSerializerOptions options)
   at HarmonyLib.HarmonySharedState.GetPatchInfo(MethodBase method)
   at HarmonyLib.PatchProcessor.GetPatchInfo(MethodBase method)
   at HarmonyLib.Harmony.<GetPatchedMethods>b__18_0(MethodBase original)
   at System.Linq.Enumerable.WhereArrayIterator`1.GetCount(Boolean onlyIfCheap)
   at System.Linq.Enumerable.Count[TSource](IEnumerable`1 source)
   at SecagentBase.HookDomainCode.InitGacHooks(Assembly gacHooks, Boolean loaderOptimizationIsSingleDomain) in C:\ProgramData\Jenkins\.jenkins\workspace\Dotnet\CSQB\Secagent\SecagentBase\HookDomainCode.cs:line 71

**Comment by pardeike** [comment]
After looking at the code I suspect that when serializing, some values might be `null` and thus the default handling is to not write them out in the json. Then, when reading, the reader expects that key=val to exist but instead the next key is presented and thus it fails by expecting a certain type.

The only fields that are written that can possibly be null are
- owner
- moduleGUID
- after
- before

The `before` and `after` arrays are defaulted to empty arrays and thus should not be a problem. The `owner` is never null but I wonder if `moduleGUID` could be null for global methods that are not part of any Type.

Can you confirm this?

**Comment by pardeike** [comment]
Please verify with master to confirm that this issue is solved

**Comment by Guluis** [comment]
System.Text.Json.JsonException: The converter 'HarmonyLib.PatchJsonConverter' read too much or not enough. Path: $.prefixes[0] | LineNumber: 0 | BytePositionInLine: 172.
   at System.Text.Json.ThrowHelper.ThrowJsonException_SerializationConverterRead(JsonConverter converter)
   at System.Text.Json.Serialization.JsonConverter`1.VerifyRead(JsonTokenType tokenType, Int32 depth, Int64 bytesConsumed, Boolean isValueConverter, Utf8JsonReader& reader)
   at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.Converters.IEnumerableDefaultConverter`2.OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, TCollection& value)
   at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.JsonPropertyInfo`1.ReadJsonAndSetMember(Object obj, ReadStack& state, Utf8JsonReader& reader)
   at System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1.OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   at System.Text.Json.JsonSerializer.ReadCore[TValue](JsonConverter jsonConverter, Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   at System.Text.Json.JsonSerializer.ReadCore[TValue](Utf8JsonReader& reader, Type returnType, JsonSerializerOptions options)
   at System.Text.Json.JsonSerializer.Deserialize[TValue](ReadOnlySpan`1 utf8Json, JsonSerializerOptions options)
   at HarmonyLib.PatchInfoSerialization.Deserialize(Byte[] bytes)
   at HarmonyLib.HarmonySharedState.GetPatchInfo(MethodBase method)
   at HarmonyLib.PatchProcessor.GetPatchInfo(MethodBase method)
   at HarmonyLib.Harmony.GetPatchInfo(MethodBase method)
   at HarmonyLib.Harmony.<GetPatchedMethods>b__18_0(MethodBase original)
   at System.Linq.Enumerable.WhereArrayIterator`1.GetCount(Boolean onlyIfCheap)
   at System.Linq.Enumerable.Count[TSource](IEnumerable`1 source)
   at SecagentBase.HookDomainCode.InitGacHooks(Assembly gacHooks, Boolean loaderOptimizationIsSingleDomain)

**Comment by Guluis** [comment]
This is the JSON that causes the issue:
{"prefixes":[{"index":0,"debug":false,"owner":"GacHooks","priority":400,"methodToken":100663303,"moduleGUID":"8b50457d-3711-4699-b375-12dcf50e4203","after":[],"before":[]}],"postfixes":[{"index":0,"debug":false,"owner":"GacHooks","priority":400,"methodToken":100663304,"moduleGUID":"8b50457d-3711-4699-b375-12dcf50e4203","after":[],"before":[]}],"transpilers":[],"finalizers":[{"index":0,"debug":false,"owner":"GacHooks","priority":400,"methodToken":100663305,"moduleGUID":"8b50457d-3711-4699-b375-12dcf50e4203","after":[],"before":[]}]}
