### ISSUE TITLE
Issues with Patches and Dependencies

### ISSUE THREAD

**Issue by Aidanamite** [pardeike/Harmony#447]
So I'm currently doing some modding for the game Unexplored and I'm experiencing an issue with interactions between the mods but only when one mod tries to call another mod's (`UsefulTools`) function in a harmony patch. It can and does call the other mod's functions just fine in its Load method before applying the patch, however when trying to apply its patch it throws an error saying that the other mod's assembly could not be loaded.

Error output: 
```
An error occured while loading
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.IO.FileNotFoundException: Could not load file or assembly 'UsefulTools, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The system cannot find the file specified.
   at System.Reflection.RuntimeAssembly._nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName assemblyRef, Evidence assemblySecurity, RuntimeAssembly reqAssembly, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.InternalLoad(String assemblyString, Evidence assemblySecurity, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean forIntrospection)
   at System.Reflection.RuntimeAssembly.InternalLoad(String assemblyString, Evidence assemblySecurity, StackCrawlMark& stackMark, Boolean forIntrospection)
   at System.Reflection.Assembly.Load(String assemblyString)
   at System.Runtime.Serialization.FormatterServices.LoadAssemblyFromString(String assemblyName)
   at System.Reflection.MemberInfoSerializationHolder..ctor(SerializationInfo info, StreamingContext context)
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.SerializationInvoke(IRuntimeMethodInfo method, Object target, SerializationInfo info, StreamingContext& context)
   at System.Runtime.Serialization.ObjectManager.CompleteISerializableObject(Object obj, SerializationInfo info, StreamingContext context)
   at System.Runtime.Serialization.ObjectManager.FixupSpecialObject(ObjectHolder holder)
   at System.Runtime.Serialization.ObjectManager.DoFixups()
   at System.Runtime.Serialization.Formatters.Binary.ObjectReader.Deserialize(HeaderHandler handler, __BinaryParser serParser, Boolean fCheck, Boolean isCrossAppDomain, IMethodCallMessage methodCallMessage)
   at System.Runtime.Serialization.Formatters.Binary.BinaryFormatter.Deserialize(Stream serializationStream, HeaderHandler handler, Boolean fCheck, Boolean isCrossAppDomain, IMethodCallMessage methodCallMessage)
   at HarmonyLib.PatchInfoSerialization.Deserialize(Byte[] bytes)
   at HarmonyLib.PatchProcessor.Patch()
   at HarmonyLib.Harmony.<PatchAll>b__10_0(Type type)
   at HarmonyLib.CollectionExtensions.Do[T](IEnumerable`1 sequence, Action`1 action)
   at HarmonyLib.Harmony.PatchAll(Assembly assembly)
   at HarmonyLib.Harmony.PatchAll()
   at ScrollCleaning.Main.Load()
   at BasicModLoader.Main.Load()
```

the mod's code is as follows:
```cs
using BasicModLoader;
using HarmonyLib;
using PhantomGrammar.GrammarCore;
using System.Collections.Generic;
using System.Reflection;
using Unexplored.Core;
using Unexplored.Core.Items;
using Unexplored.Core.Mobs.Components;
using System.Linq;
using System.Reflection.Emit;
using UsefulTools;
using Tools = UsefulTools.Tools;

namespace ScrollCleaning
{
	[ModInfo("ScrollCleaning", "Scroll Cleaning", "1.0.0", new string[] { "UsefulTools 1.0" }, new string[] { "UsefulTools" })]
	public class Main : Mod
	{
		public static ScrollType UsedScroll = (ScrollType)21;
		public override void Load()
		{
			EnumPatcher.AddEnumValue("Used", UsedScroll);
			Tools.RegisterScroll(UsedScroll, 0, 0, 0, 99, 0, 0);
			Tools.RegisterRecipe(
				(x) => x is Scroll && (x as Scroll).Type == UsedScroll,
				(x) => x is Potion && (x as Potion).Type == PotionType.HotWater,
				(x, y) => new Item[] {
					Tools.ItemFactoryCreate(new Symbol(null, "scroll(type='Blank',count=1)", true), GameManager.Instance.Player.Position, true),
					Tools.ItemFactoryCreate(new Symbol(null, "flask(count=1)", true), GameManager.Instance.Player.Position, true)
				}, true, true, true);
			new Harmony("com.aidanamite.ScrollCleaning").PatchAll();
			Log("Loaded");
		}
		internal static void Log(object message) => Log<Main>(message);
	}

	[HarmonyPatch(typeof(Scroll),"Read")]
	class Patch_ScrollRead
    {
		static void Prefix(Scroll __instance)
		{
			Item item = Tools.ItemFactoryCreate(new Symbol(null, "scroll(type='Used',count=1)", true), __instance.Owner.Position, true);
			Inventory inventory = __instance.Owner.GetComponentByType<Inventory>();
			if (inventory != null)
			{
				inventory.Unlock();
				if (!inventory.TryPickUp(item, false))
				{
					__instance.Owner.Parent.AddComponent(item);
				}
				inventory.Lock();
			}
		}
	}

	[HarmonyPatch(typeof(Scroll), "Use")]
	class Patch_TryUseScroll
	{
		static IEnumerable<CodeInstruction> Transpiler(IEnumerable<CodeInstruction> instructions, ILGenerator ilg)
		{
			var code = instructions.ToList();
			var c = code.FindIndex((v) => v.opcode == OpCodes.Ldfld && v.operand is FieldInfo && (v.operand as FieldInfo).Name == "Type") + 2;
			var l = ilg.DefineLabel();
			code.Insert(c++, new CodeInstruction(OpCodes.Beq_S, l));
			code.Insert(c++, new CodeInstruction(OpCodes.Ldarg_0));
			code.Insert(c++, new CodeInstruction(OpCodes.Ldfld, AccessTools.Field(typeof(Scroll), "Type")));
			code.Insert(c++, new CodeInstruction(OpCodes.Ldc_I4_S, (int)Main.UsedScroll));
			code[c + 1].labels.Add(l);
			return code;
		}
	}
}
```

I suppose I might be able to work around this issue by setting up a method in my mod's code that would call the method from UsefulTools however I'm not understanding why this error is occuring

**Comment by Aidanamite** [comment]
After some messing around I found that doing an indirect call to the methods (putting methods that call the methods in my main class and calling those) did not fix the error. However if i stored the prefixes code in a `System.Action<Scroll>` object and invoking it in the prefix worked fine

**Comment by pardeike** [comment]
It might be that you are calling that other mods methods too early and it’s not loaded yet. Or the game has a custom assembly loader that somehow does not get involved. 

The main reason is that when you patch a method that some other mod has already patched, Harmony needs to reapply all existing patches to construct the new replacement method. You can see that in the stacktrace as it tries to deserialise patch information and fails at that point because it cannot load the assembly.

**Comment by Aidanamite** [comment]
It definitely isn't that the other mod isn't loaded yet because my code calls several of the mod's methods before calling the patch and those run without issue.

After a quick test based on your responce, yeah it seems that the issue is related to applying the second patch to the method.

Unfortunate issue but I've found a way around it. Out of curiosity, would you know how to load the mod's assembly in a way that wouldn't have this issue? For context, the mod loader is one that I designed and this is the first issue related the assembly loading that I've encountered, the current method I'm using is just a `Assembly.LoadFrom(file);`.

**Comment by pardeike** [comment]
You might need to implement https://docs.microsoft.com/en-us/dotnet/standard/assembly/resolve-loads

**Comment by Aidanamite** [comment]
I'm certain that the mod was compiled pointing to the correct assembly. Also thanks for the tip with the assembly resolver, it's worked a treat
