### ISSUE TITLE
Exception when using a transpiler on a .NET 6 dll

### ISSUE THREAD

**Issue by dannoe** [pardeike/Harmony#503]
**Describe the bug**
I was using a transpiler to change the behavior of an external dll. The dll provider was using .NET FX 4.8 in the past and is now using .NET 6.
It was working with .NET 4.8 and is now failing with .NET 6. I am getting an ``MissingMethodException`` exception (see below) after calling``Patch``.

**To Reproduce**
1. The original method and its signature and class
```csharp
internal class CodeActionServiceLoader
{
    ...
    public CodeActionServiceLoader()
    {
        HashSet<Assembly> builder = new HashSet<Assembly>();
        this.analyzersFolderPath = CodeActionServiceLoader.GetPathToAnalyzerFolder();
        this.LoadDefaultAssemblies(builder);
        this.LoadAnalyzerAssemblies(builder);
        this.compositionContext = (CompositionContext) new ContainerConfiguration().WithAssemblies((IEnumerable<Assembly>) builder).CreateContainer();
    }

    private void LoadDefaultAssemblies(HashSet<Assembly> builder) => this.LoadAssemblies((IEnumerable<string>) this.defaultAssemblyNames, builder, new Func<string, Assembly>(this.TryAssemblyLoad));
    ...
}
```
3. The patch code
see https://github.com/dannoe/BusinessCentral.LinterCop/blob/add-code-actions/Patches/CodeActionServiceLoaderPatcher.cs
4. The output of the Harmony debug log
```
### Harmony id=LinterCop.BusinessCentral, version=2.2.1.0, location=c:\Users\<redacted>\.vscode\extensions\ms-dynamics-smb.al-10.0.687650\bin\Analyzers\0Harmony.dll, env/clr=6.0.6, platform=Win32NT, ptrsize:runtime/env=8/Bits64, Windows
### Started from static System.Void BusinessCentral.LinterCop.Patches.CodeActionServiceLoaderPatcher::Patch(), location c:\Users\<redacted>\.vscode\extensions\ms-dynamics-smb.al-10.0.687650\bin\Analyzers\BusinessCentral.LinterCop.dll
### At 2022-10-27 04.21.05
```
5. The stacktrace or other errors
```
System.TypeInitializationException: The type initializer for 'HarmonyLib.HarmonySharedState' threw an exception.
 ---> System.MissingMethodException: Method not found: 'Void System.Reflection.Emit.ILGenerator.MarkSequencePoint(System.Diagnostics.SymbolStore.ISymbolDocumentWriter, Int32, Int32, Int32, Int32)'.
   at MonoMod.Utils._DMDEmit.Generate(DynamicMethodDefinition dmd, MethodBase _mb, ILGenerator il)
   at MonoMod.Utils.DMDEmitDynamicMethodGenerator._Generate(DynamicMethodDefinition dmd, Object context)
   at MonoMod.Utils.DMDGenerator`1.Generate(DynamicMethodDefinition dmd, Object context)
   at MonoMod.RuntimeDetour.Platforms.DetourRuntimeILPlatform..ctor()
   at MonoMod.RuntimeDetour.Platforms.DetourRuntimeNETPlatform..ctor()
   at MonoMod.RuntimeDetour.Platforms.DetourRuntimeNETCorePlatform..ctor()
   at MonoMod.RuntimeDetour.Platforms.DetourRuntimeNETCorePlatform.Create()
   at MonoMod.RuntimeDetour.DetourHelper.get_Runtime()
   at HarmonyLib.HarmonySharedState..cctor()
   --- End of inner exception stack trace ---
   at HarmonyLib.HarmonySharedState.GetPatchInfo(MethodBase method)
   at HarmonyLib.PatchProcessor.Patch()
   at HarmonyLib.Harmony.Patch(MethodBase original, HarmonyMethod prefix, HarmonyMethod postfix, HarmonyMethod transpiler, HarmonyMethod finalizer)
   at BusinessCentral.LinterCop.Patches.CodeActionServiceLoaderPatcher.Patch()
   at BusinessCentral.LinterCop.Patches.CodeActionServiceLoaderPatcher.TryPatch()
   at BusinessCentral.LinterCop.Design.Rule0001FlowFieldsShouldNotBeEditable..ctor()
   at System.RuntimeType.CreateInstanceDefaultCtor(Boolean publicOnly, Boolean wrapExceptions)
```

**Expected behavior**
No exception being thrown.

**Runtime environment (please complete the following information):**
 - OS: Windows 11, 64bit
 - .NET 6
 - Harmony version 2.2.1
- Name of game or host application: https://marketplace.visualstudio.com/items?itemName=ms-dynamics-smb.al

**Additional context**
The method mentioned is indeed missing in .NET 6:
https://learn.microsoft.com/de-de/dotnet/api/system.reflection.emit.ilgenerator.marksequencepoint?view=netframework-4.8#system-reflection-emit-ilgenerator-marksequencepoint(system-diagnostics-symbolstore-isymboldocumentwriter-system-int32-system-int32-system-int32-system-int32)
![grafik](https://user-images.githubusercontent.com/7450586/198314490-03d754a6-4dd5-49e9-8ed6-822d41f40915.png)

**Comment by pardeike** [comment]
What build of Harmony are you using? If you use nuget it will automatically pick the .NET 5/6 version but if you choose it manually you might have picked a different version that is compiled against a code base where this method does exist.

**Comment by dannoe** [comment]
I feel dumb now. 😅 The dll that was hosting harmony was still compiled for .net48 and so it was grabbing the .net48 version of harmony. Thanks for the hint.

**Comment by pardeike** [comment]
You learned something, which is good!
