### ISSUE TITLE
Incorrect code generation for exception block when patching `System.Net.WebClient::DownloadFile(System.Uri address, System.String fileName)`

### ISSUE THREAD

**Issue by guneysus** [pardeike/Harmony#563]
When I try to patch `System.Net.WebClient::DownloadFile(System.Uri address, System.String fileName)`, `InvalidOperationException` is being thrown.

**Steps to reproduce:**

```csharp
using HarmonyLib;

namespace HarmonyIssueReproduce
{
    internal class Program
    {
        static void Main(string[] args)
        {
            Harmony.DEBUG = true;

            var harmony = new Harmony("issue-reproduce");

            var original = typeof(System.Net.WebClient)
                .GetMethods()
                .Where(x => x.FullDescription() == "System.Void System.Net.WebClient::DownloadFile(System.Uri address, System.String fileName)")
                .First();

            var interceptor = typeof(Hooks).GetMethod(nameof(Hooks.Interceptor));

            try
            {
                _ = harmony.Patch(original: original, prefix: new HarmonyMethod(interceptor));

            }
            catch (Exception)
            {
                throw;
            }

        }
    }
}

public static class Hooks
{
    public static void Interceptor()
    {
    }
}
```

**Runtime environment (please complete the following information):**
 - Windows 11, 64bit
 - .NET 60
 - Harmony 2.2.2

**Additional context**
Prefix, postfix and finalizer: All of them throws this exception.
And also I found that the methodss below are not patcheable:

```
System.Void System.Net.WebClient::DownloadFileAsync(System.Uri address, System.String fileName, System.Object userToken)
System.Void System.Net.WebClient::UploadFileAsync(System.Uri address, System.String method, System.String fileName, System.Object userToken)
```

The exception seems thrown in here:

https://github.com/mono/mono/blob/main/mcs/class/corlib/System.Reflection.Emit/ILGenerator.cs#L928C7-L928C7

**Stack Trace**
```
System.InvalidOperationException
  HResult=0x80131509
  Message=Incorrect code generation for exception block.
  Source=System.Private.CoreLib
  StackTrace:
   at System.Reflection.Emit.ILGenerator.EndExceptionBlock()
   at MonoMod.Utils._DMDEmit.Generate(DynamicMethodDefinition dmd, MethodBase _mb, ILGenerator il)
   at MonoMod.Utils.DMDEmitDynamicMethodGenerator._Generate(DynamicMethodDefinition dmd, Object context)
   at MonoMod.Utils.DynamicMethodDefinition.Generate(Object context)
   at HarmonyLib.MethodPatcher.CreateReplacement(Dictionary`2& finalInstructions)
   at HarmonyLib.PatchFunctions.UpdateWrapper(MethodBase original, PatchInfo patchInfo)
   at HarmonyLib.PatchProcessor.Patch()
   at HarmonyIssueReproduce.Program.Main(String[] args) in C:\repos\ahmed.guneysu\sandbox\HarmonySandbox\HarmonyIssueReproduce\Program.cs:line 22

```

**harmony.log**

```
### Harmony id=issue-reproduce, version=2.2.2.0, location=C:\repos\ahmed.guneysu\sandbox\HarmonySandbox\HarmonyIssueReproduce\bin\Debug\net6.0\0Harmony.dll, env/clr=6.0.26, platform=Win32NT, ptrsize:runtime/env=8/Bits64, Windows
### Started from static System.Void HarmonyIssueReproduce.Program::Main(System.String[] args), location C:\repos\ahmed.guneysu\sandbox\HarmonySandbox\HarmonyIssueReproduce\bin\Debug\net6.0\HarmonyIssueReproduce.dll
### At 2024-01-12 12.27.35
### Patch: System.Void System.Net.WebClient::DownloadFile(System.Uri address, System.String fileName)
### Replacement: static System.Void System.Net.WebClient::System.Net.WebClient.DownloadFile_Patch1(System.Net.WebClient this, System.Uri address, System.String fileName)
IL_0000: Local var 0: System.Net.WebRequest
IL_0000: Local var 1: System.IO.FileStream
IL_0000: Local var 2: System.Boolean
IL_0000: Local var 3: System.Net.WebRequest
IL_0000: Local var 4: System.Exception
IL_0000: call       static System.Void Hooks::Interceptor()
IL_0005: // start original
IL_0005: ldarg.1
IL_0006: ldstr      "address"
IL_000B: call       static System.Void System.ArgumentNullException::ThrowIfNull(System.Object argument, System.String paramName)
IL_0010: ldarg.2
IL_0011: ldstr      "fileName"
IL_0016: call       static System.Void System.ArgumentNullException::ThrowIfNull(System.Object argument, System.String paramName)
IL_001B: ldnull
IL_001C: stloc.0
IL_001D: ldnull
IL_001E: stloc.1
IL_001F: ldc.i4.0
IL_0020: stloc.2
IL_0021: ldarg.0
IL_0022: call       System.Void System.Net.WebClient::StartOperation()
.try
{
	.try
	{
		IL_0027: ldarg.2
		IL_0028: ldc.i4.2
		IL_0029: ldc.i4.2
		IL_002A: newobj     System.Void System.IO.FileStream::.ctor(System.String path, System.IO.FileMode mode, System.IO.FileAccess access)
		IL_002F: stloc.1
		IL_0030: ldarg.0
		IL_0031: ldarg.0
		IL_0032: ldarg.0
		IL_0033: ldarg.1
		IL_0034: call       System.Uri System.Net.WebClient::GetUri(System.Uri address)
		IL_0039: callvirt   virtual System.Net.WebRequest System.Net.WebClient::GetWebRequest(System.Uri address)
		IL_003E: dup
		IL_003F: stloc.3
		IL_0040: stfld      System.Net.WebRequest System.Net.WebClient::_webRequest
		IL_0045: ldloc.3
		IL_0046: stloc.0
		IL_0047: ldarg.0
		IL_0048: ldloc.0
		IL_0049: ldloc.1
		IL_004A: call       System.Byte[] System.Net.WebClient::DownloadBits(System.Net.WebRequest request, System.IO.Stream writeStream)
		IL_004F: pop
		IL_0050: ldc.i4.1
		IL_0051: stloc.2
		IL_0052: leave =>   Label0
		IL_0057: leave =>   (autogenerated)
	} // end try
	.filter
	{
		IL_005C: isinst     System.Exception
		IL_0061: dup
		IL_0062: brtrue =>  Label1
		IL_0067: pop
		IL_0068: ldc.i4.0
		IL_0069: br =>      Label2
		IL_006E: Label1
		IL_006E: stloc.s    4 (System.Exception)
		IL_0070: ldloc.s    4 (System.Exception)
		IL_0072: isinst     System.OutOfMemoryException
		IL_0077: ldnull
		IL_0078: cgt.un
		IL_007A: ldc.i4.0
		IL_007B: ceq
		IL_007D: ldc.i4.0
		IL_007E: cgt.un
		IL_0080: Label2
		IL_0080: endfilter
		IL_0082: pop
		IL_0083: ldloc.0
		IL_0084: call       static System.Void System.Net.WebClient::AbortRequest(System.Net.WebRequest request)
		IL_0089: ldloc.s    4 (System.Exception)
		IL_008B: isinst     System.Net.WebException
		IL_0090: brtrue =>  Label3
		IL_0095: ldloc.s    4 (System.Exception)
		IL_0097: isinst     System.Security.SecurityException
		IL_009C: brfalse => Label4
		IL_00A1: Label3
		IL_00A1: rethrow
		IL_00A3: Label4
		IL_00A3: call       static System.String System.SR::get_net_webclient()
		IL_00A8: ldloc.s    4 (System.Exception)
		IL_00AA: newobj     System.Void System.Net.WebException::.ctor(System.String message, System.Exception innerException)
		IL_00AF: throw
		IL_00B0: leave =>   (autogenerated)
	} // end handler
	IL_00B2: leave =>   (autogenerated)
} // end try
.finally
{
	IL_00B7: ldloc.1
	IL_00B8: brfalse => Label5
	IL_00BD: ldloc.1
	IL_00BE: callvirt   virtual System.Void System.IO.Stream::Close()
	IL_00C3: ldloc.2
	IL_00C4: brtrue =>  Label6
	IL_00C9: ldarg.2
	IL_00CA: call       static System.Void System.IO.File::Delete(System.String path)
	IL_00CF: Label5
	IL_00CF: Label6
	IL_00CF: ldarg.0
	IL_00D0: call       System.Void System.Net.WebClient::EndOperation()
	IL_00D5: endfinally
	IL_00D6: leave =>   (autogenerated)
} // end handler
IL_00D7: // end original
IL_00D7: Label0
IL_00D7: ret
DONE


```

**DownloadFile method**

```csharp
        public void DownloadFile(Uri address, string fileName)
        {
            ArgumentNullException.ThrowIfNull(address);
            ArgumentNullException.ThrowIfNull(fileName);

            WebRequest? request = null;
            FileStream? fs = null;
            bool succeeded = false;
            StartOperation();
            try
            {
                fs = new FileStream(fileName, FileMode.Create, FileAccess.Write);
                request = _webRequest = GetWebRequest(GetUri(address));
                DownloadBits(request, fs);
                succeeded = true;
            }
            catch (Exception e) when (!(e is OutOfMemoryException))
            {
                AbortRequest(request);
                if (e is WebException || e is SecurityException) throw;
                throw new WebException(SR.net_webclient, e);
            }
            finally
            {
                if (fs != null)
                {
                    fs.Close();
                    if (!succeeded)
                    {
                        File.Delete(fileName);
                    }
                }
                EndOperation();
            }
        }
```

**Comment by pardeike** [comment]
Harmony does not support original methods that use the `where` clause in a catch block

**Comment by pardeike** [comment]
As explained here: <https://learn.microsoft.com/en-us/dotnet/api/system.reflection.emit.ilgenerator.beginexceptfilterblock>
WONTFIX for now until I get the time to rewrite the whole method generation with Cecil
