### ISSUE TITLE
Transpiler: JIT Compiler fails on unmodified method

### ISSUE THREAD

**Issue by HoLLy-HaCKeR** [pardeike/Harmony#71]
I'm working on a small project where I patch a few methods at runtime through a modified DLL. I had 2 transpilers that both do some kind of modification and worked perfectly. I then tried to add a third transpiler for a third method but that one keeps failing during the patching, even if I immediately return the `IEnumerable<CodeInstruction>` without any modifications.

I tried to copy the method from dnSpy to a test project to reproduce it, cutting out most code that referenced other fields or classes, but I couldn't reproduce the issue there. I'm using .NET Framework 4.0 (not through Mono/Unity) on Win10.

Harmony fails while trying to compile the transpiled method, at [this line](https://github.com/pardeike/Harmony/blob/master/Harmony/Tools/DynamicTools.cs#L115):
```cs
m__CompileMethod.Invoke(null, new object[] { runtimeMethodInfo });
```

For the sake of completeness, here's how I invoked Harmony:
```cs
MethodInfo target = /**/;

var hInst = HarmonyInstance.Create("holly.test");
hInst.Patch(target, null, null, new HarmonyMethod(typeof(PatchClass), nameof(DummyTranspiler)));

//direct copy from HarmonyTests:
public static IEnumerable<CodeInstruction> DummyTranspiler(MethodBase original, IEnumerable<CodeInstruction> instructions)
{
    // no-op / passthrough
    return instructions;
}
```

Stacktrace:
```
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.InvalidProgramException: JIT Compiler encountered an internal limitation.
   at System.Runtime.CompilerServices.RuntimeHelpers._CompileMethod(IRuntimeMethodInfo method)
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
   at Harmony.DynamicTools.PrepareDynamicMethod(DynamicMethod method)
   at Harmony.MethodPatcher.CreatePatchedMethod(MethodBase original, List`1 prefixes, List`1 postfixes, List`1 transpilers)
   at Harmony.PatchFunctions.UpdateWrapper(MethodBase original, PatchInfo patchInfo)
   at Harmony.PatchProcessor.Patch()
   at Harmony.HarmonyInstance.Patch(MethodBase original, HarmonyMethod prefix, HarmonyMethod postfix, HarmonyMethod transpiler)
   at <snip>.Main()
```

**Comment by pardeike** [comment]
Never seen a “internal limitation” JIT error :-/

**Comment by HoLLy-HaCKeR** [comment]
It seems to happen when you create an invalid IL body and try to JIT it. I had it happen to me when making mistakes in my transpiling, generally when editing branch targets. 

My first thought was that Harmony loses some information related to branches/labels or exception handler regions, but recreating the method in a fresh project didn't fix it so I'm not quite sure what causes it. My target was mildly obfuscated (mostly symbol names), so perhaps it uses some aggressive/hacky optimization tricks that Harmony doesn't expect.

I would try to use prefix/postfix patches, but the target method's parameters have obfuscated names so that sadly won't work.

**Comment by pardeike** [comment]
I assume you have tried the debug mode to analyse the generated IL code. Also, I personally haven’t implemented try/catch support but someone added a pull request. I will continue to work on that but have too much going on right now.

**Comment by pardeike** [comment]
I have preliminary support for try/catch ready to be tested so I want to give you a headsup. As soon as its stable you can test your patch on the new released version.

**Comment by HoLLy-HaCKeR** [comment]
Just dropped the latest master in the project I was working on and there are no exceptions during patching anymore! The patched code doesn't do exactly what I expected but that's most likely an error on my end. I think this issue can be closed then, unless you want to keep it open until you're satisfied with your implementation.
